import PDFDocument from 'pdfkit';
import type { PurchaseInput } from './types';

/**
 * Render a carrier-compliant shipping label PDF (4x6 inch, ZPL-friendly layout).
 * Returns the raw PDF bytes. Pure Node — no headless browser.
 */
export function renderLabelPdf(opts: {
  carrierDisplayName: string;
  serviceDisplayName: string;
  trackingNumber: string;
  input: PurchaseInput;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    // 4" x 6" = 288 x 432 PDF points
    const doc = new PDFDocument({ size: [288, 432], margin: 14, layout: 'portrait' });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header bar
    doc.rect(0, 0, 288, 30).fill('#0a0b0f');
    doc.fillColor('#ffffff').fontSize(13).text('ONSECTIVE', 14, 9, { width: 260 });
    doc.fillColor('#d4a93f').fontSize(8).text(opts.carrierDisplayName.toUpperCase(), 14, 23, { width: 260 });

    let y = 44;
    doc.fillColor('#000000').fontSize(9).text('SHIP FROM', 14, y);
    y += 11;
    const o = opts.input.origin;
    doc.fontSize(8).text(`${o.fullName}\n${o.line1}${o.line2 ? `\n${o.line2}` : ''}\n${o.city}, ${o.region} ${o.postalCode}\n${o.country}`, 14, y, { width: 260 });

    y += 60;
    doc.fontSize(9).text('SHIP TO', 14, y);
    y += 11;
    const d = opts.input.destination;
    doc.fontSize(11).text(d.fullName, 14, y, { width: 260 });
    y += 14;
    doc.fontSize(11).text(`${d.line1}${d.line2 ? `\n${d.line2}` : ''}`, 14, y, { width: 260 });
    y += d.line2 ? 28 : 14;
    doc.fontSize(11).text(`${d.city}, ${d.region} ${d.postalCode}`, 14, y, { width: 260 });
    y += 14;
    doc.fontSize(12).text(d.country, 14, y, { width: 260 });

    y += 22;
    doc.rect(14, y, 260, 1).fill('#000000');

    y += 8;
    doc.fillColor('#000000').fontSize(8).text('SERVICE', 14, y);
    doc.fontSize(11).text(opts.serviceDisplayName, 14, y + 9, { width: 260 });

    y += 30;
    doc.fontSize(8).text('TRACKING NUMBER', 14, y);
    doc.fontSize(13).text(opts.trackingNumber, 14, y + 9, { width: 260 });

    y += 30;
    doc.fontSize(8).text('WEIGHT', 14, y);
    doc.fontSize(10).text(`${(opts.input.weightGrams / 1000).toFixed(2)} kg`, 14, y + 9);

    y += 30;
    // Barcode placeholder (text-encoded). Real production uses bwip-js; left abstract here.
    doc.rect(14, y, 260, 50).stroke('#000000');
    doc.fontSize(8).text('|||||  ' + opts.trackingNumber + '  |||||', 14, y + 20, { width: 260, align: 'center' });

    y += 60;

    // Phase 5: customs block — only printed when cross-border AND at least one line has HSN.
    const crossBorder =
      opts.input.origin.country &&
      opts.input.destination.country &&
      opts.input.origin.country.toUpperCase() !== opts.input.destination.country.toUpperCase();
    const customs = (opts.input.customs ?? []).filter((c) => !!c.hsnCode);
    if (crossBorder && customs.length > 0) {
      doc.fillColor('#000000').fontSize(8).text('CUSTOMS DECLARATION', 14, y);
      y += 10;
      doc.fontSize(7).text('Item · HSN · Origin · Qty · Unit value', 14, y, { width: 260 });
      y += 9;
      for (const line of customs.slice(0, 5)) {
        const value = (line.unitValueMinor / 100).toFixed(2);
        doc.fontSize(7).text(
          `${truncate(line.description, 28)} · ${line.hsnCode ?? '—'} · ${line.tariffCountry ?? '—'} · ${line.qty} · ${value} ${line.currency}`,
          14,
          y,
          { width: 260 },
        );
        y += 9;
      }
      if (customs.length > 5) {
        doc.fontSize(7).text(`+ ${customs.length - 5} more line(s)`, 14, y, { width: 260 });
        y += 9;
      }
      y += 4;
    }

    doc.fontSize(7).fillColor('#666666').text(
      `Order: ${opts.input.orderId} · Shipment: ${opts.input.shipmentId} · Generated by Onsective`,
      14,
      y,
      { width: 260, align: 'center' },
    );

    doc.end();
  });
}

function truncate(s: string, n: number): string {
  return s.length <= n ? s : s.slice(0, n - 1) + '…';
}
